### PR TITLE
fix: fallback to selecting first controller during refresh, if None selected

### LINKED ISSUE #116: TUI suddenly empty?
Hi,

As of today I see an empty TUI when I open `bluetui`, it was working fine before

OS: _Arch Linux x86_64_
Kernel: _Linux 6.18.5-arch1-1_

**Screenshot of TUI**
Image

### PR DESCRIPTION
**Pull request by sermuns**
Fixes #116.

### CODE REVIEW

File: src/app.rs [hunk 1]
```diff
@@ -806,6 +808,13 @@ impl App {
                 }
             } else {
                 // Add new detected adapters
+
+                // Coming from having NO adapters (e.g. having suspended), no adapter is selected.
+                // This makes it fallback select the FIRST controller.
+                // TODO: ideally we would remember what controller was selected before...
+                if self.controllers.is_empty() && self.controller_state.selected().is_none() {
+                    self.controller_state.select_first();
+                }
```
Comment (sermuns) [inline src/app.rs:817]: I'm not super-happy about falling back to first controller. I guess most people only have one bluetooth controller so maybe it doesn't matter.
